title: gipert's sheet music
email: luigi.pertoldi@hotmail.it
description:
    it: >
      Nel tempo libero mi diverto a trascrivere la musica che amo.
      Ecco la mia collezione di spartiti, tutti autoprodotti.
    en: >
      My self-produced sheet music collection. Enjoy!
baseurl: "/sheet-music"
url: "https://gipert.github.io"
github_username: gipert/sheet-music

# Build settings
markdown: kramdown
permalink: pretty

google_analytics: UA-129302942-1

plugins:
  - jekyll-sitemap
