# Site settings
title: gipert's sheet music
#email: luigi.pertoldi@hotmail.it
description: > # this means to ignore newlines until "baseurl:"
  I really enjoy transcribing a piece of good music, when it comes.
  Here's my collection of sheet music, all produced by myself.
baseurl: "/sheet-music" # the subpath of your site, e.g. /blog
url: "https://gipert.github.io" # the base hostname & protocol for your site
github_username:  gipert

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-analytics

jekyll_analytics:
  GoogleAnalytics:
    id: UA-129302942-1
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking
