title: gipert's sheet music
email: luigi.pertoldi@hotmail.it
description:
    it: >
      Nel tempo libero mi diverto a trascrivere la musica che amo.
      Ecco la mia collezione di spartiti, tutti autoprodotti.
    en: >
      I really enjoy transcribing a good piece of music, when it comes.
      Here's my collection of sheet music, all self-produced.
baseurl: "/sheet-music"
url: "https://gipert.github.io"
github_username: gipert

# Build settings
markdown: kramdown
permalink: pretty

google_analytics: UA-129302942-1
